### ISSUE TITLE
TODO postlaunch or whenevs maybe

### ISSUE THREAD

**Issue by rachelbasse** [rachelbasse/haseebq#2]
- [ ] test mailchimp, social add
- [x] fix seo tags
- [ ] change header
- [ ] change preview
- [ ] add gcse
- [x] Change font sans family to PT Sans
- [x] Reduce font size a bit and adjust interdependent settings accordingly
- [x] add syntax highlighting for fenced code blocks
